<style>
    .latam-title {
            display: inline;
            padding: 20px;
        }
</style>
<div style="text-align: center;">
    <img src="https://download.logo.wine/logo/LATAM_Paraguay/LATAM_Paraguay-Logo.wine.png" alt="LATAM-LOGO" width="200" style="display: inline"/>      
    <h1 style="display: inline;">LATAM Challenge Development</h1>
</div>
<center>
<em>With love by Nicolás Zenteno Guardia</em>
</center>
<center>
<em>August 29th, 2023</em>
</center>
<p><em>Summary:-</em> This work shows the development of the LATAM Challenge sent to the candidates for the "Data Scientist" position. The problem to be solved consists in predicting the probability of delay of the flights that land or take off from the airport of Santiago de Chile
(SCL) using public and real data where each row corresponds to a flight that landed or took off
from SCL during 2017. For this we separe the problem in 5 parts</p>

<ol>
    <li> 
        <a href="#EDA">Exploratory Data Analysis:</a> How is the data distributed? Is there any noteworthy insight to share? What are the  conclusions?
    </li>
    <li> <a href="#DATA_PREP">Data Preparation:</a> Generation of aditional columns, new variables and others.</li>
    <li> <a href="#DELAY_RATE">Pre-Modelling Delay-Rate Understanding:</a> Understanding of the behavior of the delay rate across destination, airline, month of the year, day of the week, season and type of flight.</li>
    <li> <a href="#MODELLING">Modelling:</a> Train different models.</li>
    <li> <a href="#EVALUATION">Evaluation:</a> Evaluate the models.</li>
</ol>

<a id="EDA"><a>
<h1>1. Exploratory Data Analysis</h1>
    <h3>1.1 Import libraries and dataset</h3>

In [3]:
import pandas as pd

file_url="https://raw.githubusercontent.com/nizent/LATAMBestCompany/main/dataset_SCL.csv"
pd.read_csv(file_url)

C:\Users\nicol\AppData\Local\Temp\ipykernel_6460\1548997351.py:4: DtypeWarning: Columns (1,6) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(file_url)

,Fecha-I,Vlo-I,Ori-I,Des-I,Emp-I,Fecha-O,Vlo-O,Ori-O,Des-O,Emp-O,DIA,MES,AÑO,DIANOM,TIPOVUELO,OPERA,SIGLAORI,SIGLADES
0,2017-01-01 23:30:00,226,SCEL,KMIA,AAL,2017-01-01 23:33:00,226,SCEL,KMIA,AAL,1,1,2017,Domingo,I,American Airlines,Santiago,Miami
1,2017-01-02 23:30:00,226,SCEL,KMIA,AAL,2017-01-02 23:39:00,226,SCEL,KMIA,AAL,2,1,2017,Lunes,I,American Airlines,Santiago,Miami
2,2017-01-03 23:30:00,226,SCEL,KMIA,AAL,2017-01-03 23:39:00,226,SCEL,KMIA,AAL,3,1,2017,Martes,I,American Airlines,Santiago,Miami
3,2017-01-04 23:30:00,226,SCEL,KMIA,AAL,2017-01-04 23:33:00,226,SCEL,KMIA,AAL,4,1,2017,Miercoles,I,American Airlines,Santiago,Miami
4,2017-01-05 23:30:00,226,SCEL,KMIA,AAL,2017-01-05 23:28:00,226,SCEL,KMIA,AAL,5,1,2017,Jueves,I,American Airlines,Santiago,Miami
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68201,2017-12-22 14:55:00,400,SCEL,SPJC,JAT,2017-12-22 15:41:00,400.0,SCEL,SPJC,JAT,22,12,2017,Viernes,I,JetSmart SPA,Santiago,Lima
68202,2017-12-25 14:55:00,400,SCEL,SPJC,JAT,2017-12-25 15:11:00,400.0,SCEL,SPJC,JAT,25,12,2017,Lunes,I,JetSmart SPA,Santiago,Lima
68203,2017-12-27 14:55:00,400,SCEL,SPJC,JAT,2017-12-27 15:35:00,400.0,SCEL,SPJC,JAT,27,12,2017,Miercoles,I,JetSmart SPA,Santiago,Lima
68204,2017-12-29 14:55:00,400,SCEL,SPJC,JAT,2017-12-29 15:08:00,400.0,SCEL,SPJC,JAT,29,12,2017,Viernes,I,JetSmart SPA,Santiago,Lima
68205,2017-12-31 14:55:00,400,SCEL,SPJC,JAT,2017-12-31 15:04:00,400.0,SCEL,SPJC,JAT,31,12,2017,Domingo,I,JetSmart SPA,Santiago,Lima